# Generated by Django 3.0 on 2020-03-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_item_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='back_img_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='back_img_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
