# Generated by Django 3.0 on 2020-03-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200330_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='back_img_url',
        ),
        migrations.RemoveField(
            model_name='team',
            name='back_img_url',
        ),
        migrations.AddField(
            model_name='game',
            name='back_img_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
