# Generated by Django 3.0 on 2020-03-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingProducts',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('product_list', models.CharField(max_length=50)),
            ],
        ),
    ]
