# Generated by Django 3.0 on 2020-03-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sale', '0002_shippingproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingTracker',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('no_of_days', models.IntegerField(default=3)),
            ],
        ),
    ]
