# Generated by Django 3.0 on 2020-03-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200324_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='product_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='purchase_id',
            field=models.UUIDField(default=12, primary_key=True, serialize=False),
        ),
    ]
