# Generated by Django 3.0 on 2020-03-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200331_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='purchase_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
